### ISSUE TITLE
BUG-016 Error: Command raised an exception: JSONDecodeError: Expecting ',' delimiter: line 1 column 851 (char 850)

### ISSUE THREAD

**Issue by 5ecrawlreporter** [5ecrawler/tracker#22] opened 2019-07-03 03:43 UTC
**What is the bug?**:  Error: Command raised an exception: JSONDecodeError: Expecting ',' delimiter: line 1 column 851 (char 850)
**Severity**:  Medium (minor functional impact)   (I guess?)
**Steps to reproduce**: Just ask it to pull a Androsphinx 
**Context**: !monster Androsphinx (See Screenshot)

- HotButthurtToast#2221
Verification: 0

**Comment by lorddusk** [comment] 2019-07-03 11:24
Duplicate of #20

**Comment by 5ecrawlreporter** [comment] 2019-07-03 11:24
Note - LordDusk#0001

Resolved - duplicate of BUG-015 (5ecrawler/tracker#20) (#20)

**Closed by lorddusk** 2019-07-03 11:24 UTC
